CREATE TABLE trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trade_type VARCHAR(255),
    trade_date DATE,
    amount DOUBLE,
    currency VARCHAR(255),
    counterparty VARCHAR(255),
    PRIMARY KEY (id)
);
