package ${packageName};

import ${modelPackage}.${modelClass};
import ${entityPackage}.${entityClass};
import org.springframework.stereotype.Component;

/**
 * Base Mapper generated by Gradle.
 * Do not modify this file. Override methods in ${mapperClass} instead.
 */
public abstract class ${className} {

    public ${modelClass} toModel(${entityClass} entity) {
        if (entity == null) {
            return null;
        }
        ${modelClass} model = new ${modelClass}();
        <% attributes.each { attr -> %>
        <% if (attr.isCalculated) { %>
        model.set${attr.capitalizedName}(calculate${attr.capitalizedName}(entity));
        <% } else { %>
        model.set${attr.capitalizedName}(entity.get${attr.capitalizedName}());
        <% } %>
        <% } %>
        return model;
    }

    public ${entityClass} toEntity(${modelClass} model) {
        if (model == null) {
            return null;
        }
        ${entityClass} entity = new ${entityClass}();
        <% attributes.each { attr -> %>
        <% if (!attr.isCalculated) { %>
        entity.set${attr.capitalizedName}(model.get${attr.capitalizedName}());
        <% } %>
        <% } %>
        return entity;
    }

    // Abstract methods for calculated fields
    <% attributes.each { attr -> %>
    <% if (attr.isCalculated) { %>
    protected abstract ${attr.type} calculate${attr.capitalizedName}(${entityClass} entity);
    <% } %>
    <% } %>
}
